[install]
# Use the exact versions specified in package.json
exact = true

# Install peer dependencies automatically
peer = true

[dev]
# Port for the dev server
port = 5173

# Open the browser automatically
open = false

# Enable hot module replacement
hot = true

# Enable source maps
sourcemap = true
