import { Act } from '@/data/acts'
import type { Region } from '@/types/region'
import {
  BaldursMouth,
  BasiliskGate,
  BloomridgePark,
  BlushingMermaid,
  Candulhallows,
  CountingHouse,
  DevilsFee,
  ElerrathinsHome,
  ElfsongTavern,
  FelogyrsFireworks,
  FlymmCargo,
  ForgeOfTheNine,
  Graveyard,
  HouseOfGrief,
  LadyJannathsEstate,
  Lodge,
  LowerCityLoc,
  LustrousLass,
  OldGarlowsPlace,
  PhilgravesMansion,
  SorcerousSundries,
  SteelWatchFoundry,
  StormshoreTabernacle,
  SzarrPalace,
  WaterQueensHouse,
  WineFestival,
} from '.'

export const LowerCity: Region = {
  id: 'lowercity',
  name: 'Lower City',
  act: Act.III,
  sublocations: [
    BaldursMouth,
    BasiliskGate,
    BloomridgePark,
    BlushingMermaid,
    Candulhallows,
    CountingHouse,
    DevilsFee,
    ElerrathinsHome,
    ElfsongTavern,
    FelogyrsFireworks,
    FlymmCargo,
    ForgeOfTheNine,
    Graveyard,
    HouseOfGrief,
    LadyJannathsEstate,
    Lodge,
    LowerCityLoc,
    LustrousLass,
    OldGarlowsPlace,
    PhilgravesMansion,
    SorcerousSundries,
    SteelWatchFoundry,
    StormshoreTabernacle,
    SzarrPalace,
    WaterQueensHouse,
    WineFestival,
  ],
}
